### PR TITLE
.NET agent can trace AppDomain/Assembly/Module/Class load and unload events

### PR DESCRIPTION
**Pull request by SunFellow**
- Implemented corresponding `CProfilerCallback` methods.
- Added `CorProfilerInfo` and `MetaDataImport` methods to request information via COM interfaces by corresponding ids.
- Added corresponding maps to `InfoHanlder` to store obtained information.
- Added methods to `InfoHanlder` to output information from the maps.

### CODE REVIEW

**Comment by Aleksandr-Kapustin-epam-com** [comment]
I recommend to follow these principles:
- If a function does something that could fail, it should throw an error, or return `bool` / `std::optional`; it should never silently ignore errors or produce half-initialized structures
- If it returns `bool` or `std::optional`, or name should start with `Try` to indicate no exceptions involved

This way, the caller of the function always knows:
- If the name of the function I call does not start with `Try`, I will probably need to catch exceptions
- If the name of the function I call starts with `Try`, I will get `bool` or `std::optional`. With `std::optional`, I will get `std::nullopt` in case of any problem. If I got some `value()` from the `std::optional`, it contains a fully working object.

I recommend to update `MetaDataImport::GetTypeName` to be `std::optional<std::wstring> TryGetTypeName` ...
This will ensure other methods calling it are not constructing partial results.

Examples of recommended kinds of function declarations:
```
// may throw
void DoWork();

// should not throw
bool TryDoWork();

struct MyStruct
{
    int x;
    std::wstring s;
}

// may throw, will return MyStruct with both x and s filled
MyStruct GetMyStruct();

// will not throw, will return std::nullopt or MyStruct with both x and s filled
std::optional<MyStruct> TrygetMyStruct();
```

* **Note**: _currently we are allocating strings in functions like_ `TryGetTypeName` _without any error handling. This may result in throwing exceptions out of functions which intended not to throw. This should be addressed separately_.

**Comment by SunFellow** [comment]
I agree excepting the followings:
> If it returns bool or std::optional, or name should start with Try to indicate no exceptions involved.

Try-like functions don't suppose not to throw exceptions at all. An exception could come from any STL operation and this way you need to handle each-and-every level. The main idea of such functions not to generate and catch exceptions on expected fails to make them light. Unexpected fails can still generate exceptions and those should be handled at higher level.
Other hand, whether a function does or doesn't throw exceptions is defined by its signature (throws() or noexcept) - not by its name.

**Comment by Aleksandr-Kapustin-epam-com** [comment]
> Try-like functions don't suppose not to throw exceptions at all. An exception could come from any STL operation and this way you need to handle each-and-every level. 

Good catch. I meant exactly this when typed `no exceptions involved`. Thank for the clarification.

**Comment by SunFellow** [comment]
Added 3 incremental commits to allow view local changes. The last one is better with ignoring whitespace changes.
Except moving of large blocks of new methods in InfoHanlder.h/.cpp, that is targeted to make the final change better.

**Pull request merged**
